import type { AgentEvent } from '../types/agent.types'
import { AgentEventItem } from './AgentEventItem'
import type { AgentToolActivity } from '../types/agent.types'
const toolLabels: Record<string, string> = { get_incident: 'Load incident', get_breakdown: 'Compare dimensions', get_timeseries: 'Analyze timeline', get_decline_reason_distribution: 'Analyze decline reasons', get_incident_history: 'Check incident history', classify_response_code: 'Classify Yuno response code', list_active_incidents: 'Compare active incidents' }
export type AgentActivityItem = { id: string; label: string; title: string; detail: string; tone: 'running' | 'success' | 'warning' | 'error' | 'neutral' }
export function AgentTimeline({ events, toolActivities = [], fallback = [] }: { events: AgentEvent[]; toolActivities?: AgentToolActivity[]; fallback?: AgentActivityItem[] }) {
  const hasRealActivity = events.length > 0 || toolActivities.length > 0
  return <div className="agent-timeline">{!hasRealActivity && fallback.length === 0 ? <div className="empty-state">No activity is available for the selected record yet.</div> : <>{hasRealActivity ? <>{events.map((event, index) => <AgentEventItem event={event} latest={index === events.length - 1 && toolActivities.length === 0} key={event.id} />)}{toolActivities.map((activity, index) => <article className={`agent-event agent-${activity.status === 'completed' ? 'success' : 'running'} ${index === toolActivities.length - 1 ? 'event-new' : ''}`} key={`${activity.toolName}-${index}`}><span className="agent-event-dot" /><div className="agent-event-card"><div className="agent-event-meta"><span className="pill neutral">TOOL</span><span>{activity.status}</span><code>{activity.toolName}</code></div><h3>{toolLabels[activity.toolName] ?? activity.toolName}</h3><p>{activity.status === 'completed' ? 'Tool completed' : 'Tool started'}</p></div></article>)}</> : fallback.map((item, index) => <article className={`agent-event agent-${item.tone} ${index === fallback.length - 1 ? 'event-new' : ''}`} key={item.id}><span className="agent-event-dot" /><div className="agent-event-card"><div className="agent-event-meta"><span className="pill neutral">{item.label}</span></div><h3>{item.title}</h3><p>{item.detail}</p></div></article>)}</>}</div>
}
