import { useAgentStreamContext } from '../context/AgentStreamContext'
import { EMPTY_ROOT_CAUSE, formatScope, formatRecurrence, formatUsdFromCents, getResponseCodePresentation } from '../utils/diagnosisFormatting'
const activityLabel = { OBSERVE: 'Currently observing', ANALYZE: 'Currently analyzing', DECIDE: 'Currently deciding', ACT: 'Currently acting', VERIFY: 'Currently verifying', INVESTIGATE: 'Currently investigating', DIAGNOSE: 'Currently diagnosing', RECOMMEND: 'Preparing recommendation', REPORT: 'Preparing report' } as const
export function AgentSummaryCard({ monitorRunning = false, earlyWarnings = 0 }: { monitorRunning?: boolean; earlyWarnings?: number }) {
  const { events, latestEvent, isRunning, currentPhase, demoStatus, startDemo, diagnosis, isSse, incidentId } = useAgentStreamContext()
  const route = [...events].reverse().find((event) => event.route)?.route; const metrics = [...events].reverse().find((event) => event.metrics)?.metrics; const decision = [...events].reverse().find((event) => event.decision)?.decision
  const country = route ? new Intl.DisplayNames(['en'], { type: 'region' }).of(route.country) ?? route.country : null
  const activity = demoStatus === 'IDLE' ? (isSse && incidentId ? 'Confirmed incident queued' : isSse && monitorRunning ? earlyWarnings > 0 ? 'Preventive investigation in progress' : 'Monitoring payment telemetry' : 'Watchtower offline') : demoStatus === 'ERROR' ? 'Analysis failed' : demoStatus === 'PAUSED' ? 'Demo paused' : demoStatus === 'COMPLETED' ? (isSse ? 'Report ready' : 'Analysis completed') : currentPhase ? activityLabel[currentPhase] : 'AI analysis running'
  const responseCode = diagnosis ? getResponseCodePresentation(diagnosis.evidence) : null
  return <article className="panel agent-summary"><div className="agent-summary-heading"><div><p className="eyebrow">AI Agent</p><h3>{activity}</h3>{route ? <p>{route.provider} · {route.paymentMethod} · {country}</p> : null}</div>{isRunning && latestEvent ? <span className="agent-live-label"><i /> LIVE</span> : null}</div>
    <div className="agent-summary-stats">{diagnosis ? <><div><span>Evidence sufficiency</span><strong>{diagnosis.evidenceStatus}</strong></div><div title="Estimated from lost approvals × average payment value over the detection window."><span>Payment volume at risk</span><strong>{formatUsdFromCents(diagnosis.impact.lossPerMinuteCents)}/min</strong></div>{responseCode?.responseCode ? <div><span>Response code</span><strong>{responseCode.responseCode}</strong></div> : null}<div><span>Approval</span><strong>{diagnosis.recommendation.requiresHumanApproval ? 'Human approval required' : 'Ready for review'}</strong></div></> : <><div><span>Approval deviation</span><strong>{metrics?.deviation !== undefined ? `${metrics.deviation}%` : '--'}</strong></div><div><span>Decision confidence</span><strong>{decision?.confidence !== undefined ? `${decision.confidence}%` : '--'}</strong></div><div><span>Risk</span><strong>{decision?.riskLevel ?? '--'}</strong></div></>}</div>
    {demoStatus === 'IDLE' && !isSse ? <button type="button" className="button primary agent-summary-link" onClick={startDemo}>Start demo</button> : demoStatus === 'COMPLETED' && !isSse ? <button type="button" className="button secondary agent-summary-link" onClick={startDemo}>Replay</button> : isSse && !incidentId ? null : demoStatus === 'ERROR' ? <button type="button" className="button secondary agent-summary-link" onClick={startDemo}>Retry analysis</button> : demoStatus === 'COMPLETED' ? <a className="button primary agent-summary-link" href={`#/agent-live?incidentId=${encodeURIComponent(incidentId ?? '')}`}>View diagnosis</a> : <a className="button ghost agent-summary-link" href={`#/agent-live?incidentId=${encodeURIComponent(incidentId ?? '')}`}>AI analysis running</a>}
    {diagnosis ? <div className="agent-diagnosis-summary"><strong>{diagnosis.rootCause?.statement ?? EMPTY_ROOT_CAUSE}</strong><span>Affected: {formatScope(diagnosis.affectedScope).join(' · ') || '—'}</span><span>{formatRecurrence(diagnosis.recurrence)}</span><span>Recommendation: {diagnosis.recommendation.action}</span></div> : null}
  </article>
}
